version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    networks:
      experimentation_net:
        aliases:
          - experimentation.api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@experimentation.db:5432/experiments
      - REDIS_URL=redis://experimentation.cache:6379/0
      - WAREHOUSE_ENDPOINT=http://experimentation.warehouse:9000
      - WAREHOUSE_ACCESS_KEY=admin
      - WAREHOUSE_SECRET_KEY=password
      - WAREHOUSE_REGION=us-east-1
      - ICEBERG_REST_URL=http://experimentation.iceberg:8181
      - DEBUG_MODE=true
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
      warehouse:
        condition: service_healthy
      rest-iceberg:
        condition: service_started

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    networks:
      experimentation_net:
        aliases:
          - experimentation.frontend
    environment:
      - API_URL=http://experimentation.api:8000
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
    depends_on:
      - api

networks:
  experimentation_net:
    external: true 