"""Adding stopped_readon

Revision ID: 86a5b3ab538e
Revises: 1c54e6721bac
Create Date: 2025-02-08 23:36:10.390320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a5b3ab538e'
down_revision: Union[str, None] = '1c54e6721bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('stopped_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'stopped_reason')
    # ### end Alembic commands ###
