"""Adding ramp up columns

Revision ID: cc2dc1913bf0
Revises: 86a5b3ab538e
Create Date: 2025-02-09 01:06:57.322243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2dc1913bf0'
down_revision: Union[str, None] = '86a5b3ab538e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('ramp_up_period', sa.Integer(), nullable=True))
    op.add_column('experiments', sa.Column('auto_stop_conditions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'auto_stop_conditions')
    op.drop_column('experiments', 'ramp_up_period')
    # ### end Alembic commands ###
